/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package irrgarten.UI;
import irrgarten.Directions;
import irrgarten.GameState;
import java.awt.Point;
import java.awt.Font;

/**
 *
 * @author daniel
 */
public class Window extends javax.swing.JFrame implements UI {
    
    private Cursors cursors;
    
    /**
     * Creates new form NewJFrame
     */
    public Window() {
        initComponents();
        Cursors cur = new Cursors(this,true);
        
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
        
        // Obtener la ubicación del panel padre y calcular la posición del diálogo
        Point location = cursorsPanel.getLocationOnScreen();
        int x = location.x + cursorsPanel.getWidth() / 2 - cur.getWidth() / 2;
        int y = location.y + cursorsPanel.getHeight() / 2 - cur.getHeight() / 2;
        cur.setLocation(x, y);
        
        this.cursors = cur;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        labyrinthPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        labyrinthTextArea = new javax.swing.JTextArea();
        mainLogPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        playersTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        monstersTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        smallLogPanel = new javax.swing.JPanel();
        currentPlayerLabel = new javax.swing.JLabel();
        endGameLabel = new javax.swing.JLabel();
        cursorsPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labyrinthTextArea.setColumns(18);
        labyrinthTextArea.setFont(new java.awt.Font("Monospaced", 0, 27)); // NOI18N
        labyrinthTextArea.setRows(5);
        jScrollPane1.setViewportView(labyrinthTextArea);

        javax.swing.GroupLayout labyrinthPanelLayout = new javax.swing.GroupLayout(labyrinthPanel);
        labyrinthPanel.setLayout(labyrinthPanelLayout);
        labyrinthPanelLayout.setHorizontalGroup(
            labyrinthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labyrinthPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        labyrinthPanelLayout.setVerticalGroup(
            labyrinthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labyrinthPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        playersTextArea.setColumns(20);
        playersTextArea.setRows(5);
        jScrollPane2.setViewportView(playersTextArea);

        monstersTextArea.setColumns(20);
        monstersTextArea.setRows(5);
        jScrollPane3.setViewportView(monstersTextArea);

        logTextArea.setColumns(20);
        logTextArea.setRows(5);
        jScrollPane4.setViewportView(logTextArea);

        javax.swing.GroupLayout mainLogPanelLayout = new javax.swing.GroupLayout(mainLogPanel);
        mainLogPanel.setLayout(mainLogPanelLayout);
        mainLogPanelLayout.setHorizontalGroup(
            mainLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        mainLogPanelLayout.setVerticalGroup(
            mainLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLogPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        currentPlayerLabel.setText("jLabel1");

        endGameLabel.setText("jLabel2");

        javax.swing.GroupLayout smallLogPanelLayout = new javax.swing.GroupLayout(smallLogPanel);
        smallLogPanel.setLayout(smallLogPanelLayout);
        smallLogPanelLayout.setHorizontalGroup(
            smallLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smallLogPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(currentPlayerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(endGameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        smallLogPanelLayout.setVerticalGroup(
            smallLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smallLogPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(smallLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentPlayerLabel)
                    .addComponent(endGameLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout cursorsPanelLayout = new javax.swing.GroupLayout(cursorsPanel);
        cursorsPanel.setLayout(cursorsPanelLayout);
        cursorsPanelLayout.setHorizontalGroup(
            cursorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        cursorsPanelLayout.setVerticalGroup(
            cursorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cursorsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labyrinthPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainLogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(smallLogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(smallLogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainLogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labyrinthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cursorsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Directions nextMove() {
	return this.cursors.getDirection();
    }

    @Override
    public void showGame(GameState gameState) {
        // Set labyrinth font to monospaced
//        int labyrinthFontSize=18;
//        Font labyrinthFont = new Font("Monospace", Font.PLAIN, labyrinthFontSize);
//        labyrinthTextArea.setFont(labyrinthFont);
        
	labyrinthTextArea.setText(gameState.getLabyrinth());
        labyrinthTextArea.setEditable(false);
        
        playersTextArea.setText(gameState.getPlayers());
        playersTextArea.setEditable(false);
        monstersTextArea.setText(gameState.getMonsters());
        monstersTextArea.setEditable(false);
	logTextArea.setText(gameState.getLog());
        logTextArea.setEditable(false);

	String auxStr = "Current Player Index: ";
	currentPlayerLabel.setText(auxStr + Integer.toString(gameState.getCurrentPlayer()));
	auxStr = "Is there a winner? : ";
        auxStr += (gameState.getWinner() ? "true" : "false");
	endGameLabel.setText(auxStr);
        
	labyrinthTextArea.repaint();
	playersTextArea.repaint();
	monstersTextArea.repaint();
	logTextArea.repaint();
	currentPlayerLabel.repaint();
	endGameLabel.repaint();

    } 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentPlayerLabel;
    private javax.swing.JPanel cursorsPanel;
    private javax.swing.JLabel endGameLabel;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel labyrinthPanel;
    private javax.swing.JTextArea labyrinthTextArea;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JPanel mainLogPanel;
    private javax.swing.JTextArea monstersTextArea;
    private javax.swing.JTextArea playersTextArea;
    private javax.swing.JPanel smallLogPanel;
    // End of variables declaration//GEN-END:variables
}
